Feature/#31 stage info api
LITO-apps/Treevel-server pull request #33
Opened 2020-10-26 14:34 UTC by takesi0627

### 対象イシュー
Close #31 

### 概要
ステージ概要で必要なAPIを用意する

### 詳細

#### 現実装になった経緯

b84cd23 : `records.min_clear_time` を `records.clear_time` に改名し、データタイプも `float` に変更
903248d : 最短クリアタイムを取得するAPIを実装
cad27b1 : ステージのクリア割合を取得するAPIを実装

#### 技術的な内容

・URLのネーミングについて：今まで決めていなかったので仕事のPJを参考にして書きました。（`stageinfo/get/avg_clear_rate`を例）
　・前段：使用する場所ステージ概要なので`stageinfo`
　・中段；`get` `create` `update` などDBに対する操作を明示
　・後段；対象データ？取りあえず詳細になるようなやつ

### キャプチャ

### 動作確認方法
**※マイグレーションを行ってください**
マイグレーションを実行したら、DBにこのようなデータが入っているはず
![image](https://user-images.githubusercontent.com/17778395/97184471-499ce980-17e2-11eb-9041-6e5d78a22475.png)

- [ ] `/stageinfo/get/all_user_min_clear_time` の動作確認
　・ `$ curl -d "stage_id=1" localhost:8080/stageinfo/get/all_user_min_clear_time # 100.02`
　・ `$ curl -d "stage_id=2" localhost:8080/stageinfo/get/all_user_min_clear_time # 50.02`  
　・ `$ curl -d "stage_id=3" localhost:8080/stageinfo/get/all_user_min_clear_time # <nil>`  

- [ ] `/stageinfo/get/avg_clear_rate` の動作確認
　・ `docker-compose exec mysql mysql -u user -p db` DBにログインする
　・ `mysql> SELECT * FROM records WHERE stage_id = 1;` でクリア状況を確認する
　・`$ curl -d "stage_id=1" localhost:8080/stageinfo/get/avg_clear_rate` クリアレートが一致するか確認する
　・`stage_id`を変えて動作確認する

### 参考 URL
[Queryの書き方](https://andrew-sledge.gitbooks.io/the-unofficial-pop-book/content/common-patterns/querying-for-certain-data.html)

2020-10-26 14:35 UTC, takesi0627 commented
@xiii111 @takasusuke 
レビューよろしくお願いします。URLのネーミングについてもコメントいただけたら幸いです。

2020-10-28 12:20 UTC, xiii111 reviewed
僕のテスト用の API の悪いところを度外視してコメントします

### `URI` について
まず，アンダースコアはドメイン名に使えないはずなので，それに合わせて `URI` には `_` ではなく `-` を使うようにしましょう（ `avg_clear_rate` → `avg-clear-rate` 的な）

次に
> ・URLのネーミングについて：今まで決めていなかったので仕事のPJを参考にして書きました。（stageinfo/get/avg_clear_rateを例）
> 　・前段：使用する場所ステージ概要なのでstageinfo
> 　・中段；get create update などDBに対する操作を明示
> 　・後段；対象データ？取りあえず詳細になるようなやつ

とありますが，中段は [HTTP メソッド](https://developer.mozilla.org/ja/docs/Web/HTTP/Methods) で再現しましょう．よって `/前段/後段` + `HTTP メソッド` という構成．また，今回は `record` のデータを軽く加工して返す API なので `URI` としては以下の方がわかりやすいと思います．
- `/stageinfo/get/all_user_min_clear_time` → `/record/{stage-id}/clear-time`

まず `stage-id` の渡し方にはパスパラメータを使いましょう（現状 post メソッドを使って data を送っちゃってます）もし，特定のユーザの `clear-time` が欲しくなったら `/record/{stage-id}/clear-time?player-id=...` みたいにクエリパラメータを使えば良い感じですね． パスパラメータとクエリパラメータの使い分けは必須かどうかがしっくりくると思います．今回は stage-id が来ないとクリアタイムが成り立たないので（ステージを跨いでクリアタイムを議論することはないので），stage-id はパスパラメータで渡す．どのユーザのクリアタイムを見るかは任意なので（全ユーザならその中で最速を返すことが可能なので）クエリパラメータを使うイメージです．

- `/stageinfo/get/avg_clear_rate` → `record/{stage-id}/clear-rate/`

こちらもパスパラメータを使いましょう． `avg` ですが特定のステージの `clear-rate` の時点で `avg` の要素があると思ったので，いらないかなと．

これに則るなら，僕のテスト用の API は以下のような `URI` になるのかなと

```
router.GET("/players", playerHandler.HandleGetAllPlayers)
router.GET("/records", recordHandler.HandleGetAllRecords)
router.POST("/player", playerHandler.HandleCreatePlayer)
router.POST("/record", recordHandler.HandleCreateRecord)
```

`httprouter` のパラメータ表現については https://qiita.com/Ken2mer/items/b19d99e03446febfd916 とか含め，色んなところにまとまってる

2020-10-28 13:12 UTC, xiii111 requested changes
細かいところまで見ていないですが，ここまでのところで一旦修正お願いします．これらが修正されたらロジックの確認をします！

2020-10-28 13:12 UTC, xiii111 commented on main.go
> +    router.POST("/stageinfo/get/avg_clear_rate", recordHandler.HandleStageInfoGetAvgClearRate)
ここは `URI` で述べたとおり．

2020-10-28 13:12 UTC, xiii111 commented on domain/repository/record.go
> +    GetStageInfoAvgClearRate(int) (float32, error)
`URI` に合わせて変えてもらえればと．

2020-10-28 13:12 UTC, xiii111 commented on handler/record.go
> +    HandleStageInfoGetAvgClearRate(http.ResponseWriter, *http.Request, httprouter.Params)
`URI` に合わせて変えてもらえたらと．

2020-10-28 13:12 UTC, xiii111 commented on handler/record.go
> +    minClearTime, err := strconv.ParseFloat(r.FormValue("min_clear_time"), 32)
モデルを `clear_time` ないし `ClearTime` に変えたなら， `min` はもう消さない？

2020-10-28 13:12 UTC, xiii111 commented on handler/record.go
> +    minClearTime, err := strconv.ParseFloat(r.FormValue("min_clear_time"), 32)
他の箇所も同様

2020-10-28 13:12 UTC, xiii111 commented on migrations/20201024121554_alter_record_clear_time.mysql.down.sql
> +ALTER TABLE records ADD COLUMN min_clear_time TIME COMMENT '最短クリア時間';
👍 👍

2020-10-28 13:12 UTC, xiii111 commented on migrations/20201024121554_alter_record_clear_time.mysql.up.sql
> +ALTER TABLE records ADD COLUMN clear_time float COMMENT '最短クリア時間';
```suggestion
ALTER TABLE records ADD COLUMN clear_time FLOAT COMMENT '最短クリア時間';
```
同値なはずだけど，今までの書き方が全大文字表現なので，合わせてもらえますか？（ `BOOLEAN` ， `INT` など）

2020-10-28 13:12 UTC, xiii111 commented on migrations/20201024121554_alter_record_clear_time.mysql.up.sql
> +ALTER TABLE records ADD COLUMN clear_time float COMMENT '最短クリア時間';
後，時間の単位を書いておいてもらっていいですか？

```suggestion
ALTER TABLE records ADD COLUMN clear_time float COMMENT '最短クリア時間 (秒)';
```
など

2020-10-28 13:12 UTC, xiii111 commented on migrations/20201024130703_stage_info_test_data.mysql.up.sql
> +INSERT INTO records VALUES (9007, 6, 2, TRUE, 0, 1, 331.45);
Insert ってまとめて出来なかったでしたっけ？

2020-10-28 13:23 UTC, xiii111 reviewed
追加

2020-10-28 13:23 UTC, xiii111 commented on migrations/20201024130703_stage_info_test_data.mysql.up.sql
> +INSERT INTO records VALUES (9007, 6, 2, TRUE, 0, 1, 331.45);
```suggestion
INSERT INTO records VALUES (9000, 1, 1, TRUE, 0, 1, 100.02);
INSERT INTO records VALUES (9001, 1, 1, TRUE, 0, 1, 200.11);
INSERT INTO records VALUES (9002, 1, 1, TRUE, 0, 1, 150.25);
INSERT INTO records VALUES (9003, 1, 1, TRUE, 0, 1, 300.45);
INSERT INTO records VALUES (9004, 1, 2, TRUE, 0, 1, 50.02);
INSERT INTO records VALUES (9005, 1, 2, TRUE, 0, 1, 133.11);
INSERT INTO records VALUES (9006, 1, 2, TRUE, 0, 1, 122.25);
INSERT INTO records VALUES (9007, 1, 2, TRUE, 0, 1, 331.45);
```

後，第二要素の `player_id` は `FOREIGN KEY (player_id) REFERENCES player(id) ON DELETE CASCADE` としているので，該当する ID の Player が居ないと Migration に失敗します．現状以下の Insert しか Migration ファイルにはないので， `player_id` は 1 にしないと普通は死にます

```
INSERT INTO players VALUES (1, 'test', 1, '2020-05-02 12:48:35', '2020-05-02 12:48:35');
```

2020-10-28 13:28 UTC, xiii111 commented
Migration には失敗しましたが， https://github.com/LITO-apps/Treevel-server/pull/33#discussion_r513437290 に挙げたような変更をすれば，以下の動作確認は問題ありませんでした 👍
- [x] `/stageinfo/get/all_user_min_clear_time` の動作確認
- [x] `/stageinfo/get/avg_clear_rate` の動作確認

2020-10-28 14:38 UTC, takesi0627 commented on migrations/20201024130703_stage_info_test_data.mysql.up.sql
> +INSERT INTO records VALUES (9007, 6, 2, TRUE, 0, 1, 331.45);
なるほど、僕多分ローカルで自分でインサートしたことあるから player_id 3~6はあった。
プレイヤーIDとステージIDが同じのレコードが複数存在するのはおかしいので、プレイヤーをインサートするマイグレーションファイルを作ります

2020-10-28 14:41 UTC, takesi0627 commented
@xiii111 
パスパラメータを使うメリットはなんですか？
解析が面倒そうなので普通にGETパラメータで良いのでは？と思いますけど

2020-10-28 14:43 UTC, xiii111 commented
Get パラメータとは？

2020-10-28 14:44 UTC, xiii111 commented
クエリパラメータのことかな？

2020-10-28 14:44 UTC, takesi0627 commented
URLの後ろに `?` で続くやつを僕はGETパラメータと認識しています（PHPでの話

2020-10-28 14:44 UTC, takesi0627 commented
> クエリパラメータのことかな？

多分そうです

2020-10-28 14:45 UTC, xiii111 commented
> URLの後ろに ? で続くやつを僕はGETパラメータと認識しています（PHPでの話

OK．上にも書いたけど，任意かどうかで分ける方がわかりやすいです．特定のステージ ID にしか紐づかないデータへの Get はパスパラメータにする方いいと思う．もちろん，クエリパラメータにする場合もあるとは思う

2020-10-28 14:48 UTC, xiii111 commented
クエリパラメータはちゃんと入ってくるかどうかが保証されていない

2020-10-28 14:50 UTC, xiii111 commented
> 解析が面倒そうなので

これは面倒じゃないはずだよ

2020-10-28 14:52 UTC, takesi0627 commented
前段の `record`か `stageinfo`の話ですが、使用する側（クライアント）からはどのDBにアクセスしているかわかる必要ないので、使用する側がどこで使うかで分けた方が分かりやすいと思ったから `stageinfo` にしたんですが、DBの名前にした方が分かりやすいですか？

後、DBの名前とURLと何か関連つけるのも危険じゃないかとも思ってる（特に知見はないけど

2020-10-28 14:53 UTC, xiii111 commented
> DBの名前

にしたいというよりは記録というものにアクセスすることがわかると思ったので

2020-10-28 19:18 UTC, xiii111 commented
@takesi0627 
ごめん． {stage-id} だけど，クエリパラメータで良いかも．解析は面倒じゃないんだけど， {stage-id} がただの int だから URI が今後一意にならない可能性が出てきちゃうわ．もし URI が `/record/stage/{stage-id}/clear-time` とかなら現状維持で良いかも．

2020-10-29 05:58 UTC, xiii111 commented
それか `/record/stage/{stage-id}` を叩けば，stage-id に関する json が返ってくるようにしても良いです
```
{
    "clear-time": 3.04,
    "clear-rate": 82.5
}
```
のように

2020-10-29 06:17 UTC, xiii111 commented
↑は一案なのでまだ良いのがあると思います．

2020-10-29 12:29 UTC, takesi0627 commented
・URLにハイフンを使う→TreeIdも合わせてハイフンに変更
・`/record/stage/{stage-id}` にする
・API全てJSONを返す
・GET -> SELECT
・POST -> INSERT、UPDATE

![image](https://user-images.githubusercontent.com/17778395/97573802-a3ddba80-1a2d-11eb-93e7-0bd46b7fed41.png)

2020-10-30 06:35 UTC, xiii111 commented
[通話のメモ] 
- 今回作成したエンドポイント以外は他 Issue で修正する

2020-10-30 06:37 UTC, xiii111 commented
レビューしていいときは Re-request ボタンを押してください．そしたらまたレビューします

2020-10-31 15:43 UTC, takesi0627 commented
`httprouter` は正規表現に対応していないのはちょっと不便を感じました。[`mux`](https://github.com/gorilla/mux) ってやつ結構使い方似てて正規表現も対応してくれるので一度検討したいです

こういう使い方したかった
```
router.GET("/record/stage/{stageId:[a-zA-Z]+-[0-9]+-[0-9]+}", recordHandler.HandleGetRecordStage)
```

2020-10-31 16:28 UTC, xiii111 commented
`gin` も有名ですね．ちょっと調べないと何が良いか分からないので時間をください

2020-10-31 23:53 UTC, takasusuke commented
- URI指定する段階で、引数の正規表現とかも指定するの一般的？
とりあえず、{stegeId}で受け取って、正しい引数かどうかチェックするかと思ってた。

- {stageId}で受け取らずに、.../{treeId}/{stageNumber}/... で受け取るのはどうなんでしょうか

- Request Bodyが空であることってチェックすべき？

2020-11-01 00:59 UTC, takesi0627 commented
record/stage/{tree-id} の URI と record/stage/{tree-id}/{stage-id もどき} の URI

2020-11-01 01:00 UTC, takesi0627 commented
・正規表現を使います
・ @xiii111 i フレームワークの再調査をお願いします

2020-11-02 06:37 UTC, xiii111 commented
@takesi0627 パッケージ調査の結果です（cc: @takasusuke ）
まず，正規表現をパスパラメータに使いたい場合には， [`mux`](https://github.com/gorilla/mux) は良いパッケージだと思いました！
その上で，正規表現が必要な状況は同様の path で handler を変えたい場合（ `/hoge/[0-9]/` と `/hoge/[^0-9]/` を別処理にしたいなど）です．しかし，今回はまだそのような状況ではなさそうなので，まだ `mux` を必要としていないのではと思いました（もちろん今後必要になったら，`mux` を入れるのは大賛成です）．どう思いますか？

2020-11-02 07:27 UTC, xiii111 commented
@takesi0627 続いて URI についてです（cc: @takasusuke ）

`record/stage/{tree-id}` と `record/stage/{tree-id}/{stage-number}` で表現しようという話になっていましたが，本当に適切かと思い，考え直してみました．

まず，記録には2種類あります．特定のプレイヤーに関する記録と，複数プレイヤー（基本的には全プレイヤーか？）に関する記録（統計情報）．なので， `record/{player-id}/...` と `record/stats/...` に分けるのはどうでしょうか．そうした場合， `clear_rate` や `min_clear_time` は `record/stats/...` に属しますね（特定のプレイヤーの話ではないから）．（余談ですが，Json レスポンスは `-` 繋ぎより `_` 繋ぎの方が一般的なようですね．`_` 繋ぎを一般にスネークケースと呼びますが）．よって，以下のようにするのはどうでしょうか？

- `/record/{player-id}/stages/{stage-id}` → 記録の中でも，特定プレイヤーの，特定 stage の情報

```
{
    "stage-id": "1-1"
    "clear_time": 12.3,    // クリアタイム
    "is_clear": true    // クリアしたかどうか
    ...
}
```

- `/record/{player-id}/stages` → 記録の中でも，特定プレイヤーの，複数 stage の情報．クエリパラメータでフィルタリングできるようにする．例えば `?tree-id=2` など．これを考えると `season-id` も欲しくなってきた

```
[
    {
        "stage-id": "1-1"
        "clear_time": 12.3,
        "is_clear": true
        ...
    },
    {
        "stage-id": "1-2"
        "clear_time": 1.3,
        "is_clear": true
        ...
    },
    ...
]
```

- `/record/stats/stages/{stage-id}` → 記録の中でも，全プレイヤーの，特定 stage の統計情報

```
{
    "stage-id": "1-1"
    "min_clear_time": 12.3,    // 最短クリアタイム
    "clear_rate": 34.6,    // クリア割合
    ...
}
```

- `/record/stats/stages` → 記録の中でも，全プレイヤーの，複数 stage の統計情報．クエリパラメータでフィルタリングできるようにする．例えば `?tree-id=2` など

```
[
    {
        "stage-id": "1-1"
        "min_clear_time": 12.3,
        "clear_rate": 34.6,
        ...
    },
    {
        "stage-id": "1-2"
        "min_clear_time": 4.3,
        "clear_rate": 54.6,
        ...
    },
    ...
]
```

どうでしょうか？

2020-11-02 07:31 UTC, xiii111 commented
@takesi0627 URI を書いていて気付いたのですが，正規表現を使いたい理由は， "同様の path で handler を変えたいから" ではなく，そもそも `stage-id` 部分が `[0-9]-[0-9]` となっていないリクエストを handle したくないからですか？結局， `[0-9]-[0-9]` としても存在しない stage-id があると思うので，別途 404 を返す処理を書く必要がありそうですが，最低限の形式を要求するという意味では正規表現を使うのもありかもしれません

2020-11-02 07:33 UTC, xiii111 commented
僕からは一旦以上です． @takasusuke @takesi0627 意見をください

2020-11-02 14:01 UTC, takesi0627 commented
## 正規表現について
> 正規表現を使いたい理由は， "同様の path で handler を変えたいから" ではなく，そもそも stage-id 部分が [0-9]-[0-9] となっていないリクエストを handle したくないからですか？

その通りですが、`stage-id` って `(Spring|Summer|Autumn|Winter)-[0-9]-[0-9]{1-2}`が正しいと思うのですが、違ったっけ
>  [0-9]-[0-9] としても存在しない stage-id があると思うので，別途 404 を返す処理を書く必要がありそうです。

これに関しては確かに必要ですが、今のどころサーバ側はステージデータ所持していないので検証する術がない。サーバ側もゲームデータ必要があると思うのでまた今後どう実装するかどこかで検討します。


## URIについて
時に異論はないが、 `stage-id` が `1-1`になってるのはすごく気になる・・

2020-11-02 14:02 UTC, takesi0627 commented
どちらにせよ正規表現は採用で良さそうと思うので、 `mux` に変える実装にしたいですが、これもまたステージ概要のAPIだけ実装すればいいですかね？

2020-11-02 14:34 UTC, takesi0627 commented
> どちらにせよ正規表現は採用で良さそうと思うので、 `mux` に変える実装にしたいですが、これもまたステージ概要のAPIだけ実装すればいいですかね？

`mux` と `httprouter` が同時に存在できないらしいので、先に既存のAPIを `mux` に移行する作業を行いたいですが、よろしいでしょうか

2020-11-03 01:40 UTC, takasusuke commented
- 正規表現で最低限のフィルタリングをしておいて、Spring1_99みたいな存在しないステージの場合はテーブルにデータ参照した時の結果をハンドリングして`400(invalid Parameter)`でも返すと良いと思いました。
- `stats`とそれ以外に分ける、の話は良いと思います。
- `stage_id`なのか`tree_id/stage_number`なのか確認。クエリパラメータで`tree_id`だけの場合は、`tree_id`の複数のステージ情報を取得して、`tree_id`と`stage_number`が与えられた時は、特定のステージ情報を取得する、という考えでよろしいでしょうか
- スネークケースは賛成です。カラム名は知りませんが、データベースやテーブル名に"-"を使えないものも世にはあった気がするので安心です。

2020-11-03 13:23 UTC, takesi0627 commented
@xiii111 @takasusuke 
[API一覧](https://docs.google.com/spreadsheets/d/1oh4YdHYF6oKe31MRhMa86-GCEEpXFirmoPyqRK0831U/edit#gid=0)を作成しました。テンプレートまだ確定ではないので、一部しか入力していません。形式など確認して何かあったらコメントいただけたらと思います。よろしくお願いします

2020-11-07 16:02 UTC, takesi0627 commented
@xiii111 @takasusuke 
修正できました。確認よろしくお願いします。

APIの仕様は[API一覧](https://docs.google.com/spreadsheets/d/1oh4YdHYF6oKe31MRhMa86-GCEEpXFirmoPyqRK0831U/edit#gid=1106869276)を参考してください。

JSONのエンコードは[この記事](https://www.spinute.org/go-by-example/json.html)を参考しました。ちょっとまだ何がベストかわからないが、一応正しく動作するはず。

2020-11-09 00:33 UTC, xiii111 approved these changes
LGTM with nits!

動作は確認できました！json で返ってきました！

```
{"clear_rate":0.8,"clear_time":100.02,"stage_id":"Spring-1-1"}
```

json の返し方やエンコードの仕方はきちんと調べないと最適解は出てこないので，今回はこれで OK です！

2020-11-09 00:33 UTC, xiii111 commented on domain/models/record.go
> +    MinClearTime    nulls.Float32   `db:"min_clear_time"`
名前ですが，結局 `Min` が付くんでしたっけ？各ステージごと，各プレイヤーごとのデータである `Record` 構造体では `Min` はつけないみたいな話だったような・・・ `Min` をつけるのは，各ステージごと，全プレイヤーのレスポンスだと認識していました！（全プレイヤーの "最短" という意味で）

2020-11-09 00:33 UTC, xiii111 commented on handler/record.go
> +    minClearTime, err := strconv.ParseFloat(r.FormValue("clear_time"), 32)
```suggestion
    minClearTime, err := strconv.ParseFloat(r.FormValue("min_clear_time"), 32)
```

2020-11-09 00:33 UTC, xiii111 commented on infrastructure/persistence/record.go
> +    clearTime, err := rp.GetStageClearTime(stageID)
```suggestion
    minClearTime, err := rp.GetStageClearTime(stageID)
```

2020-11-09 00:33 UTC, xiii111 commented on infrastructure/persistence/record.go
> +        "clear_time": clearTime,
```suggestion
        "min_clear_time": minClearTime,
```

2020-11-09 00:33 UTC, xiii111 commented on usecase/record.go
> +    err := ru.recordRepository.CreateRecord(playerID, stageID, isClear, playTimes, firstClearTimes, clearTime)
```suggestion
func (ru recordUseCase) CreateRecord(playerID int, stageID string, isClear bool, playTimes int, firstClearTimes nulls.Int, minClearTime nulls.Float32) error {
    err := ru.recordRepository.CreateRecord(playerID, stageID, isClear, playTimes, firstClearTimes, minClearTime)
```

2020-11-09 00:33 UTC, xiii111 commented on handler/record.go
> +    ret, err := rh.recordUseCase.GetStageStat(stageID)
同意しなかったらスキップで良いです👍

2020-11-09 02:55 UTC, takesi0627 commented on handler/record.go
> +    ret, err := rh.recordUseCase.GetStageStat(stageID)
`result` のつもりで書いてたんですが、たしかに `return` ととらえがちな。
ちなみにですけど、ほかの言語だと略語はあんまり使わない方がいいとされてると思うんですが、 `go` は略語を推奨って感じですか？なんかサンプルコード結構略している気がする

2020-11-09 13:41 UTC, xiii111 commented on handler/record.go
> +    ret, err := rh.recordUseCase.GetStageStat(stageID)
`result` か笑 あんま知見持ち合わせてないし，今回はこれでいいや

2020-11-09 13:47 UTC, takesi0627 commented on handler/record.go
> +    ret, err := rh.recordUseCase.GetStageStat(stageID)
今まで結構見かけたから使ってるんだけど、ずっと`result`だと思って使ってるが、`return value` が正しいっぽい
![image](https://user-images.githubusercontent.com/17778395/98548915-73bfd280-22dd-11eb-90f6-fb151cef5495.png)

https://qiita.com/Ted-HM/items/7dde25dcffae4cdc7923

2020-11-09 13:48 UTC, xiii111 commented on handler/record.go
> +    ret, err := rh.recordUseCase.GetStageStat(stageID)
じゃあ `result` としよう

2020-11-09 14:27 UTC, takasusuke approved these changes
動作確認しました👍

2020-11-09 14:32 UTC, merged

2020-11-09 14:32 UTC, takesi0627 commented
あざっす